#!/usr/bin/python
import argparse
import boto
import boto.ec2
import os
import sys
import time
import urllib2

from datetime import datetime
from operator import attrgetter

def get_instance_id():
    return urllib2.urlopen('http://169.254.169.254/latest/meta-data/instance-id').read()

"""Call a function, retrying on failures"""
def retry(f, retries=3):
    failures = 0
    while True:
        try:
            result = f()            
            return result
        except Exception as e:
            failures = failures + 1
            if failures > retries:
                raise         
            time.sleep(1)    
    
"""Call a boto connection function using the AWS environment variables. This supports both
ordinary and delegated credentials"""
def connect_to_ec2(region):
    if (None <> os.environ.get('AWS_DELEGATION_TOKEN')):
        return boto.ec2.connect_to_region(region, aws_access_key_id=os.environ['AWS_ACCESS_KEY'], aws_secret_access_key=os.environ['AWS_SECRET_KEY'], security_token = os.environ['AWS_DELEGATION_TOKEN'])
    elif (None <> os.environ.get('AWS_ACCESS_KEY')):
        return boto.ec2.connect_to_region(region, aws_access_key_id=os.environ['AWS_ACCESS_KEY'], aws_secret_access_key=os.environ['AWS_SECRET_KEY'])
    else:
        return boto.ec2.connect_to_region(region)

"""Parse the commandline"""
def parse_commandline():
    parser = argparse.ArgumentParser(description='Take a snapshot of EBS volumes')
    parser.add_argument('--instance', help='The instance the volume(s) are attached to. Defaults to the current instance.')
    parser.add_argument('--region', default='us-east-1', help='The region the instance is in. Defaults to us-east-1.')
    parser.add_argument('type', help='The type of snapshot (e.g. "daily").')
    parser.add_argument('keep', help='The number of snapshots to keep (e.g. 7).')
    args = parser.parse_args()
    return args

def main(args):
    args = parse_commandline()
    time = datetime.utcnow().isoformat()
    ec2 = connect_to_ec2(args.region)
    if (None == args.instance):
    	os.system('/bin/sync')
        instance_id = get_instance_id()
    else:
        instance_id = retry(lambda: ec2.get_all_instances(filters={'tag:Name': args.instance, 'instance-state-name': 'running'}))[0].instances[0].id
    print 'making backup of type %s, keeping %s for instance %s' % (args.type, args.keep, instance_id)
    volumes = retry(lambda: ec2.get_all_volumes(filters={'attachment.instance-id': instance_id}))
    for v in volumes:
         print 'volume %s is attached' % v.id
         # Get the existing snapshots before we create the new one
         volume_name = retry(lambda: ec2.get_all_tags(filters={'resource-id': v.id, 'key': 'Name'}))[0].value
         old_snapshots = retry(lambda: ec2.get_all_snapshots(filters={'tag:Name': volume_name, 'tag:Type': args.type}))
         old_snapshots = sorted(old_snapshots, key=attrgetter('start_time'))
         snapshot_description = '%s %s (%s)' % (volume_name, time, args.type)
         print 'creating snapshot \'%s\'' % snapshot_description
         snapshot = retry(lambda: ec2.create_snapshot(v.id, snapshot_description))
         print 'created snapshot %s' % snapshot.id
         retry(lambda: ec2.create_tags([snapshot.id], {'Name': volume_name, 'Instance': instance_id, 'Date': time, 'Type': args.type, 'Volume': v.id}))
         to_delete = len(old_snapshots) - int(args.keep)
         for i in range(to_delete):
             print 'deleting snapshot %s \'%s\'' % (old_snapshots[i].id, old_snapshots[i].description)
             retry(lambda: old_snapshots[i].delete())

if __name__ == "__main__":
    main(sys.argv)
