#!/bin/bash
NAME=$1
/bin/nice -n 19 /usr/bin/ionice -c 3 s3cmd sync --no-check-md5 --delete-removed  '--rexclude=.*/cache/.*' '--rexclude=.*/tmp/.*' '--rexclude=.*/pgcache/.*' /var/www/html/ s3://com.bernews.backup/$NAME/html/
